# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\"D\n\x12TransactionRequest\x12\x0e\n\x06PaidBy\x18\x01 \x01(\t\x12\x0e\n\x06PaidTo\x18\x02 \x01(\t\x12\x0e\n\x06\x41mount\x18\x03 \x01(\x02\"+\n\x13TransactionResponse\x12\x14\n\x0c\x43onfirmation\x18\x01 \x01(\x08\x32R\n\x10MoneyTransaction\x12>\n\x0fMakeTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONREQUEST._serialized_start=21
  _TRANSACTIONREQUEST._serialized_end=89
  _TRANSACTIONRESPONSE._serialized_start=91
  _TRANSACTIONRESPONSE._serialized_end=134
  _MONEYTRANSACTION._serialized_start=136
  _MONEYTRANSACTION._serialized_end=218
# @@protoc_insertion_point(module_scope)
